# Artificial Neural Network

### Importing the libraries

In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
tf.__version__

'2.17.1'

essential for performing calculations in neural networks.

## Part 1 - Data Preprocessing

### Importing the dataset

In [9]:
dataset = pd.read_csv('/content/Salary_Data.csv')
dataset


YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [13]:
X = dataset.drop(columns=['Salary'])
y = dataset.iloc[:, -1].values

In [14]:
print(X)

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5


In [15]:
print(y)

[ 39343.  46205.  37731.  43525.  39891.  56642.  60150.  54445.  64445.
  57189.  63218.  55794.  56957.  57081.  61111.  67938.  66029.  83088.
  81363.  93940.  91738.  98273. 101302. 113812. 109431. 105582. 116969.
 112635. 122391. 121872.]


In [16]:
y.shape


(30,)

### Encoding categorical data

Label Encoding the "Gender" column

In [23]:
from sklearn.impute import SimpleImputer

# Assuming 'YearsExperience' is the first column (index 0)
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# Fit the imputer on the desired column of the DataFrame
imputer.fit(X.iloc[:, [0]]) # Use iloc to select the first column

# Transform the desired column and update the DataFrame
X.iloc[:, [0]] = imputer.transform(X.iloc[:, [0]])

In [40]:
print(X)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0
  (5, 5)	1.0
  (6, 6)	1.0
  (7, 7)	1.0
  (8, 7)	1.0
  (9, 8)	1.0
  (10, 9)	1.0
  (11, 10)	1.0
  (12, 10)	1.0
  (13, 11)	1.0
  (14, 12)	1.0
  (15, 13)	1.0
  (16, 14)	1.0
  (17, 15)	1.0
  (18, 16)	1.0
  (19, 17)	1.0
  (20, 18)	1.0
  (21, 19)	1.0
  (22, 20)	1.0
  (23, 21)	1.0
  (24, 22)	1.0
  (25, 23)	1.0
  (26, 24)	1.0
  (27, 25)	1.0
  (28, 26)	1.0
  (29, 27)	1.0


One Hot Encoding the "Geography" column

In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Assuming X is your input data and it's a 2D array or DataFrame
# Re-load your original data before applying OneHotEncoder

# Define the ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

# Fit and transform the data, and convert to a dense array if needed
# Use the original data here, instead of the modified 'X'
X_transformed = ct.fit_transform(dataset[['YearsExperience']])

# Convert the sparse matrix to a dense array (if applicable)
X_dense = X_transformed.toarray()  # Convert to a dense array

# Now X_dense is the dense representation of your transformed data
print(X_dense)


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0

In [48]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

### Splitting the dataset into the Training set and Test set

In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_dense, y, test_size = 0.2, random_state = 42)

### Feature Scaling

In [51]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [52]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [53]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [54]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [55]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [56]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [57]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - accuracy: 0.0417 - loss: -17.8716
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 0.0417 - loss: -18.1776
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.0417 - loss: -18.4845
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.0417 - loss: -18.7928
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 0.0417 - loss: -19.1001
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.0417 - loss: -19.4083
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.0417 - loss: -19.7180
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.0417 - loss: -20.0295
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - accuracy: 0.0417 - loss: -20.3426
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 261ms/step - accuracy: 0.0417 - loss: -20.6573
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.0417 - loss: -20.9739
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/ste

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [59]:
print(ann.predict(sc.transform(X_dense)) > 0.5)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step
[[ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [60]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
[[ 1 25]
 [ 1 16]
 [ 1 26]
 [ 1 18]
 [ 1 14]
 [ 1 10]]


In [62]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(random_state=42)  # Or DecisionTreeRegressor for regression
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [66]:
prediction = model.predict(sc.transform([[3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])) # Reshape input to have 28 features
print(prediction)

if (prediction[0]== 0):
  print('The Person will not purchase')
else:
  print('The Person will purchase')

[4]
The Person will purchase


In [67]:
y_pred = model.predict(X_test)
# Directly reshape y_pred, assuming it is a numpy array
y_pred_array = y_pred.reshape(-1, 1)

# Convert y_test to a numpy array and reshape it, regardless of its original type
y_test_array = np.array(y_test).reshape(-1, 1)

# Concatenate arrays along the second axis (column-wise concatenation)
combined_array = np.concatenate((y_pred_array, y_test_array), axis=1)
print(combined_array)

[[15 25]
 [15 16]
 [15 26]
 [15 18]
 [ 5 14]
 [15 10]]


### Making the Confusion Matrix

In [68]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0]]


0.0